#pragma once
#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_HEIGHT 960
#define SCREEN_WIDTH 960

#define TILE_WIDTH 20
#define TILE_HEIGHT 20

#define SLIDE_DECELERATION 0.02f

#define PLAYER_WIDTH 36
#define PLAYER_HEIGHT 48

#define JUMP_SPEED 14
#define MOVE_SPEED 4
#define ACCELERATION_SPEED 1
#define STOP_SPEED 0.5f

#define GRAVITATIONAL_FORCE 0.5f
#endif